// javascript/vue.js/MEVN/App-MEVN/src/app/components/App.vue
<template>

    <div>
        <nav class="navbar navbar-light bg-light">
            <a href="/" class="navbar-brand">MEVN STACK</a>
        </nav>

        <div class="container">
            <div class="row pt-5">
                <div class="col-md-5">
                    <div class="card">
                        <div class="card-body">
                            <form @submit.prevent="sendTask">
                                <div class="form-group">
                                    <input type="text" placeholder="Insert a task" class="form-control"  v-model="task.title">
                                </div>
                                <div class="form-group">
                                    <textarea id="txt" cols="30" rows="10" class="form-control" v-model="task.description"></textarea>
                                </div>
                                <template v-if="edit ===false">
                                    <button class="btn btn-block btn-primary">SEND</button>
                                </template>
                                <template v-else>
                                    <button class="btn btn-block btn-primary">UPDATE</button>
                                </template>                                
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Task</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="t of tasks" v-bind:key="t._id">
                                <td>{{t.title}}</td>
                                <td>{{t.description}}</td>
                                <td><button class="btn btn-danger" @click="deleteTask(t._id)">Delete</button></td>
                                <td><button class="btn btn-info" @click="editTask(t._id)">Edit</button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>                
            </div>
        </div>
    </div>
    
</template>

<script>

    class Task{
        constructor(title, description){
            this.title = title;
            this.description = description;
        }
    }

    export default{
        data(){
            return{
                task: new Task(),
                tasks :[],
                edit: false,
                taskToEdit : ''
            }
        },
        created() {
            this.getTask();
        },
        methods:{
            getTask(){
                fetch('/api/tasks', {
                    method :'GET'
                })
                .then(res=> res.json())
                .then(data=> {
                        this.tasks=data;                        
                })
            },
            sendTask(){

                if(this.edit){
                    fetch('/api/tasks/' + this.taskToEdit, {
                        method : 'PUT',
                        body : JSON.stringify(this.task),
                        headers:{
                                'Accept': 'application/json',
                                'Content-Type': 'application/json'
                        }
                    })
                    .then(res=> res.json())
                    .then (data=>{
                        console.log(data);
                        this.edit = false;
                        this.getTask();
                    });

                }else{
                    fetch('/api/tasks',{
                        method : 'POST',
                        body: JSON.stringify(this.task),
                        headers :{
                                'Accept': 'application/json',
                                'Content-Type': 'application/json'
                            }
                    })
                        .then(res=> 
                            res.json()
                        )
                        .then(data=>
                            console.log(data)
                        )
                }                

                this.task= new Task();
                this.getTask();
            },
            deleteTask(id){
                fetch('/api/tasks/'+ id,{
                    method: 'DELETE',
                    headers : {
                        'Accept': 'application/json',
                        'Content-Type': 'application/json'
                    }
                })
                .then(res=> res.json())
                .then(data=> {
                    console.log(data);
                    this.getTask();
                })
            },
            editTask(id){
               fetch('/api/tasks/' + id, {
                   method : 'GET'
               })
               .then(res=> res.json())
               .then(data=>{
                   this.task = new Task(data.title, data.description);
                   this.taskToEdit = data._id;
                   this.edit = true;
               });               
            }            
        }        
    }
    
</script>

<style lang="css">
    #txt{
        resize: none
    }
</style>

// javascript/react.js/MERN/src/app/App.js
import React, {Component} from 'react';


class App extends Component{
    

    constructor(){
        super();
        this.state={
            _id: "",
            title : "",
            description : "",
            tasks: [],
            url: "/api/tasks",
            editable : false            
        };        
    }

    addTask(e){
        
        if(this.state._id){
            fetch(`${this.state.url}/${this.state._id}`, {
                method: "PUT",
                body: JSON.stringify({
                    title: this.state.title,
                    description: this.state.description
                }),
                headers:{
                    'Accept' : 'application/json',
                    'Content-Type': 'application/json' 
                }

            }).then(res=> res.json())
            .then(data=>{
                window.M.toast({html: "Task updated", classes:"rounded indigo"});
                this.setState({_id: '', title: '', description: '', editable: false});
                this.getTasks();
            }).catch(err=>{console.log(err)});

        }else{
            fetch(this.state.url, {
                method: "POST",
                body : JSON.stringify({
                    title: this.state.title,
                    description: this.state.description
                }),
                headers:{
                    'Accept' : 'application/json',
                    'Content-Type': 'application/json' 
                }
                
            }).then(res => res.json())
            .then(data=>{
                console.log(data);
                window.M.toast({html:"Task saved", classes: 'rounded indigo'});
                this.setState({title: "", description: ""});                
                this.getTasks();
            })
            .catch(err=> {
                console.log(err);                          
            });
        }

        e.preventDefault();       
    }

    componentDidMount(){
        this.getTasks();
    }

    deleteTask(id){        
        if(confirm("Are you sure you want to delete it?")){
            fetch(`${this.state.url}/${id}`, {
                method : "DELETE",
                headers:{
                    'Accept' : 'application/json',
                    'Content-Type': 'application/json' 
                }
            }).then(res=> res.json())
            .then(data=>{
                M.toast({html:"Task deleted", classes: 'rounded indigo'});
                this.getTasks();
    
            }).catch(err=> console.log(err))
        }
    }

    handleChange(e){
        const {name, value} = e.target;
        this.setState({
            [name] : value
        });
    }

    getTasks(){
        fetch(this.state.url, {
            method: "GET"
        }).then(res=> res.json())
        .then(data=> {           
            this.setState({tasks : data});            
        });
    }

    editTask(id){
        fetch(`${this.state.url}/${id}`,{
            method : "GET"
        }).then(res=> res.json())
        .then(data=>{
            this.setState({
                _id: data._id,
                title: data.title,
                description: data.description,
                editable: true                
            })            
        }).catch(err=> console.log(err));
        
    }

    render(){
        const isEditable = this.state.editable;
        let button;

        if(isEditable){
            button = <button type="submit" className="btn waves-effect waves-light indigo ">
                        Actualizar
                        <i className="material-icons right">send</i>
                    </button>
            
        }else{
            button = <button type="submit" className="btn waves-effect waves-light indigo ">
                        Crear
                        <i className="material-icons right">send</i>
                    </button>
        }

        return(
            <div>
                {/*Navigation */}
                <nav className="indigo ">
                    <div className="container">
                    <a href="/" className="brand-logo">CRUD</a>
                    </div>
                </nav>

                <div className="container">

                    <div className="row">
                        <div className="col s12 m5">
                            <div className="card">
                                <div className="card-content">
                                    <form onSubmit={this.addTask.bind(this)}>

                                        <div className="row">
                                            <div className="input-field col s12">
                                                <input type="text" id="task-title" name="title" autoFocus 
                                                onChange={this.handleChange.bind(this)} value={this.state.title}
                                                placeholder="Título de la Tarea"/>
                                                
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="input-field col s12">
                                                <textarea type="text" id="txt-description" name="description" 
                                                    className="materialize-textarea" 
                                                    onChange={this.handleChange.bind(this)} value={this.state.description}
                                                    placeholder="Descripción">
                                                </textarea>                                                                                               
                                            </div>
                                        </div>
                                        {button}
                                     </form>
                                </div>
                            </div>
                        </div>

                        <div className="col s12 m7">
                            <table>
                                <thead>
                                    <tr>
                                        <th>T&iacute;tulo</th>
                                        <th>Descripci&oacute;n</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {
                                        this.state.tasks.map((task)=>{
                                            return(
                                                <tr key={task._id}>
                                                    <td>{task.title}</td>
                                                    <td>{task.description}</td>
                                                    <td>
                                                        <button className="btn waves-effect waves-light red darken-1" 
                                                                onClick={this.deleteTask.bind(this, task._id)}
                                                        >
                                                            <i className="material-icons">delete</i>
                                                        </button>
                                                        &nbsp;                                                        
                                                        <button className="btn waves-effect waves-light  blue accent-4" 
                                                                
                                                                onClick={this.editTask.bind(this, task._id)}
                                                        >
                                                            <i className="material-icons">edit</i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            )                                        
                                        })
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>                
               
            </div>
              
        )
    }
}

export default App;
